# Generated by Django 5.2.1 on 2025-07-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailverificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_xp",
            field=models.PositiveIntegerField(
                default=0, help_text="Total experience points earned"
            ),
        ),
    ]
