# Generated by Django 5.2.1 on 2025-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_total_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="total_xp",
            field=models.PositiveIntegerField(
                default=0, help_text="Cached total XP for performance"
            ),
        ),
    ]
