# Generated by Django 5.2.1 on 2025-06-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_coursepayment_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepayment",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
