# Generated by Django 5.2.1 on 2025-06-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_subscriptionplan_usersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="courses.usercourseenrollment",
            ),
        ),
    ]
