# Generated by Django 5.2.1 on 2025-07-03 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_usersubscription_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload video file directly",
                null=True,
                upload_to="courses/videos/",
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="courses/video_thumbnails/"
            ),
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="courses/resources/")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("doc", "Word Document"),
                            ("ppt", "Presentation"),
                            ("code", "Code File"),
                            ("dataset", "Dataset"),
                            ("image", "Image"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("is_downloadable", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.courselesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("lesson", "order")},
            },
        ),
    ]
