# Generated by Django 5.2.1 on 2025-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0006_courselesson_video_file_courselesson_video_thumbnail_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courselesson",
            name="video_url",
        ),
        migrations.AddField(
            model_name="courselesson",
            name="video_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Video file size in bytes"
            ),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="video_duration",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Video duration in seconds (auto-detected when possible)",
            ),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload video file (MP4, WebM, AVI, MOV supported)",
                null=True,
                upload_to="courses/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Upload custom video thumbnail (auto-generated if not provided)",
                null=True,
                upload_to="courses/video_thumbnails/",
            ),
        ),
    ]
