# Generated by Django 5.2.1 on 2025-06-29 11:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="attachments",
            field=models.FileField(
                blank=True, null=True, upload_to="tutorials/attachments/"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, help_text="Optional video tutorial URL"),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="tutorials/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
