# Generated by Django 5.2.1 on 2025-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_add_challenge_table_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengetable",
            name="table_name",
            field=models.CharField(
                blank=True,
                help_text="Original table name (auto-extracted from schema SQL and auto-prefixed with challenge ID for isolation)",
                max_length=100,
            ),
        ),
    ]
