# Generated by Django 5.2.1 on 2025-06-29 11:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="sample_data",
            field=models.FileField(
                blank=True,
                help_text="Upload CSV or SQL file with sample data",
                null=True,
                upload_to="challenges/sample_data/",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="hint",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="question",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
