# Generated by Django 5.2.1 on 2025-07-01 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0003_challenge_sample_data_alter_challenge_description_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="company",
            field=models.CharField(
                blank=True,
                help_text="Company associated with this challenge",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="subscription_type",
            field=models.CharField(
                choices=[("free", "Free"), ("paid", "Paid")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="tags",
            field=models.JSONField(
                default=list,
                help_text="List of tags for categorization (e.g., ['joins', 'aggregation'])",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("extreme", "Extreme Hard"),
                ],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ChallengeSubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("1_month", "1 Month"),
                            ("3_months", "3 Months"),
                            ("6_months", "6 Months"),
                            ("unlimited", "Unlimited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="List of features for this plan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_recommended", models.BooleanField(default=False)),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "price"],
                "unique_together": {("duration",)},
            },
        ),
        migrations.CreateModel(
            name="UserChallengeSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending Payment"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expiry_notification_sent", models.BooleanField(default=False)),
                ("final_notification_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="challenges.challengesubscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "plan")},
            },
        ),
    ]
