# Generated by Django 5.2.1 on 2025-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0004_challenge_company_challenge_subscription_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchallengesubscription",
            name="pending_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When pending payment expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="userchallengesubscription",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
