# Generated by Django 5.2.1 on 2025-07-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0005_userchallengesubscription_pending_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userchallengesubscription",
            unique_together=set(),
        ),
    ]
