# Generated by Django 5.2.1 on 2025-07-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_alter_userchallengesubscription_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="database_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Database schema information for this challenge",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="initialization_sql",
            field=models.TextField(
                blank=True,
                help_text="SQL commands to initialize the challenge database",
            ),
        ),
    ]
