# Generated by Django 5.2.1 on 2025-07-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_challenge_database_schema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="engine_specific_sql",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Engine-specific initialization SQL (e.g., {'postgresql': 'CREATE TABLE...', 'mysql': 'CREATE TABLE...'})",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="supported_engines",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of supported database engines for this challenge (e.g., ['sqlite', 'postgresql', 'mysql'])",
            ),
        ),
    ]
