# Generated by Django 5.2.1 on 2025-07-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0008_challenge_engine_specific_sql_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="database_schema",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="engine_specific_sql",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="initialization_sql",
        ),
        migrations.AddField(
            model_name="challenge",
            name="custom_database_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom database schema information (only used for custom schema type)",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="custom_initialization_sql",
            field=models.TextField(
                blank=True,
                help_text="Custom SQL commands (only used for custom schema type)",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="database_schema_type",
            field=models.CharField(
                choices=[
                    ("employees", "Employee Database"),
                    ("ecommerce", "E-commerce Database (Orders & Returns)"),
                    ("custom", "Custom Schema"),
                ],
                default="employees",
                help_text="Select a predefined database schema for this challenge",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="supported_engines",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of supported database engines for this challenge",
            ),
        ),
    ]
