# Generated by Django 5.2.1 on 2025-07-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0010_migrate_to_simplified_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="database_schema_type",
            field=models.CharField(
                choices=[
                    ("employees", "Employee Database"),
                    ("ecommerce", "E-commerce Database (Orders & Returns)"),
                    ("students", "Student Database (Students, Courses, Enrollments)"),
                    ("custom", "Custom Schema"),
                ],
                default="employees",
                help_text="Select a predefined database schema for this challenge",
                max_length=20,
            ),
        ),
    ]
